version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  atme-app-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: atme-app-api


    depends_on:
      - db
    ports:
      - "8080:8080"
    command: /bin/bash -c "cd /server/api/ && uvicorn main:app --host=0.0.0.0 --port=8080 --reload"
    env_file:
      - api.env
    volumes:
      - ./api:/server/api/

  atme-auth-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: atme-auth-api

    depends_on:
      - db
      - atme-auth-redis

    command: /bin/bash -c "cd /server/auth/ && uvicorn main:app --host=0.0.0.0 --port=80 --reload"
    env_file:
      - auth.env

    ports:
      - "8000:80"
    volumes:
      - ./auth:/server/auth/

  atme-auth-redis:
    image: redis
    container_name: atme-auth-redis
    expose:
      - 6379
    volumes:
      - redis-data:/data/


volumes:
  db-data:
  redis-data:


