version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile


    depends_on:
      - db
    ports:
      - "8080:8080"
    command: /bin/bash -c "python /server/api/main.py"
    env_file:
      - api.env

  atme-auth-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile

    depends_on:
      - db

    command: /bin/bash -c "cd /server/auth/app/ && uvicorn main:app --host=0.0.0.0 --port=80 --reload"
    env_file:
      - auth.env

    ports:
      - "80:80"

  atme-auth-redis:
    image: redis
    container_name: atme-auth-redis
    expose:
      - 6379
    volumes:
      - redis-data:/data/


volumes:
  db-data:
  redis-data:


