version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atme
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile


    depends_on:
      - db
    ports:
      - "8080:8080"



volumes:
  db-data:


