version: '3'
services:
  atme-auth-api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: atme-auth-api
    volumes:
      - ./app/:/src/
    env_file:
      - .env
    restart: always
    ports:
      - 8000:80