"""Add relation

Revision ID: 4042e27e2f06
Revises: f9c4f69c572e
Create Date: 2024-02-19 02:50:02.679642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4042e27e2f06'
down_revision: Union[str, None] = 'f9c4f69c572e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tasks', 'users', ['localId'], ['localId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    # ### end Alembic commands ###
