"""Add Event

Revision ID: c15bcbbf78e3
Revises: 
Create Date: 2024-02-20 23:53:53.673759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15bcbbf78e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('kind', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('etag', sa.TEXT(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('selfLink', sa.TEXT(), nullable=True),
    sa.Column('parent', sa.TEXT(), nullable=True),
    sa.Column('position', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('completed', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('localId', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('displayname', sa.TEXT(), nullable=True),
    sa.Column('photoIcon', sa.TEXT(), nullable=True),
    sa.Column('refleshToken', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('localId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('localId')
    )
    op.create_table('worktimeDate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('targetDate', sa.Date(), nullable=False),
    sa.Column('worktimeStart', sa.Time(), nullable=False),
    sa.Column('worktimeEnd', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worktimeWeek',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worktimeStart', sa.Time(), nullable=False),
    sa.Column('worktimeEnd', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendarId', sa.TEXT(), nullable=True),
    sa.Column('htmlLink', sa.TEXT(), nullable=True),
    sa.Column('starttime', sa.TIMESTAMP(), nullable=False),
    sa.Column('endtime', sa.TIMESTAMP(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('Taskid', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['Taskid'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskList',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('kind', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('selfLink', sa.TEXT(), nullable=True),
    sa.Column('etag', sa.TEXT(), nullable=True),
    sa.Column('localId', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['localId'], ['users.localId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskList')
    op.drop_table('calendar')
    op.drop_table('worktimeWeek')
    op.drop_table('worktimeDate')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
