"""Add TaskList

Revision ID: f9c4f69c572e
Revises: dead9d89afac
Create Date: 2024-02-19 02:47:41.737879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c4f69c572e'
down_revision: Union[str, None] = 'dead9d89afac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskList', sa.Column('localId', sa.String(length=25), nullable=True))
    op.create_unique_constraint(None, 'taskList', ['id'])
    op.create_foreign_key(None, 'taskList', 'users', ['localId'], ['localId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskList', type_='foreignkey')
    op.drop_constraint(None, 'taskList', type_='unique')
    op.drop_column('taskList', 'localId')
    # ### end Alembic commands ###
